spring:
  application:
    name: financial-tracker
  main:
    web-application-type: none
  datasource:
    url: jdbc:sqlite:financial_tracker.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect

application:
  title: "Financial tracker"
  width: 1280.0
  height: 900.0
