package com.jakubdeniziak.financialtracker.entity;

public enum AssetType {

    CASH_PHYSICAL,
    CASH_VIRTUAL,

    BOND_TREASURY,
    BOND_CORPORATE,

    STOCK_COMMON,

    FUNDS_MUTUAL,
    FUNDS_ETF,
    FUNDS_INDEX,
    FUNDS_HEDGE,

    COMMODITY_METALS_PRECIOUS,
    COMMODITY_METALS_INDUSTRIAL,
    COMMODITY_ENERGY_OIL,

    REAL_ESTATE_PERSONAL,
    REAL_ESTATE_RESIDENTIAL,
    REAL_ESTATE_COMMERCIAL,

    CRYPTO_COIN_NORMAL,
    CRYPTO_COIN_STABLE,
    CRYPTO_COIN_MEME,

    OTHER

}
